{% set name = "pytest-regtest" %}
{% set version = "1.4.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db3c359bb161182fbd13771c4b62937ace459b2259b251e6b0cce1481362fca4

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - pytest >=4.1.0
    - python

test:
  commands:
    - "py.test --traceconfig | grep pytest-regtest-{{version}}"

about:
  home: https://gitlab.com/uweschmitt/pytest-regtest
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: pytest plugin for regression tests
  dev_url: https://gitlab.com/uweschmitt/pytest-regtest

extra:
  recipe-maintainers:
    - danieljahn
    - dbast
